
name: Build Container

on:
  push:
    paths:
      - '**.go'

jobs:
  release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - uses: ko-build/setup-ko@v0.6
      - name: ko build
        env:
          KO_DOCKER_REPO: ghcr.io/DeltaLaboratory
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ko build --platform=all -B -t latest -t ${{ github.sha }} -t ${{ github.ref_name }} .

  debug:
    if: github.event_name == 'push' && !contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - uses: ko-build/setup-ko@v0.6
      - name: ko build
        env:
          KO_DOCKER_REPO: ghcr.io/DeltaLaboratory
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ko build --platform=all -B -t debug -t ${{ github.sha }} .